### PR TITLE
Monitoring upgrade

### PR DESCRIPTION
**Pull request by mroda88**

### CODE REVIEW

**Comment by eflumerf** [comment]
How would you suggest I go about testing this? Are there updates needed in appfwk/listrev to use the new classes?

**Comment by mroda88** [comment]
Hi @eflumerf , sorry for the late reply. I was travelling. So, no need to add listrev or appfwk. This PR has the building blocks necessary to start making the changes in appfwk and listrev, so for now they are not needed. 
I would add kafkaopmon in the working area though, as those changes are a set with these, although having only opmonlib should not break the compilation. 

To test this, there are a number of integration tests already. Those are the tests I would run. The question is: are those unittests enough? Do we have concerns and some unittests need to be pushed further? This is why I wanted to know who the reviewers are, to start discussing this. I believe this should be the focus of the review. Running the unittests is just a matter of seconds. 

To test the changes on kafkaopmon, there are test apps: opmon_publisher_test and opmon_subscriber_test. 

On this PR I think we should also take time and check if the documentation on MonitorableObject is clear enough. As that is the interface exposed to the developers I think it has to be as good as we can. That's why it's already written in doxygen format. But of course it might not be enough and an external point of view is necessary. I expect to write full documentation including how schemas should be written. I was planning to do that once listrev is ready. But if the current system is too diffcult to understand, of course full documentation should be included in this PR.

**Comment by eflumerf** [comment]
It might be worth doing an editorial pass on the markdown files already in `docs/` to remove references to the old schema.

**Comment by mroda88** [comment]
Initial documentation added.

**Review by eflumerf — APPROVED** [review]
Approving, based on unit tests and documentation updates.

**Comment by mroda88** [comment]
Great, let's wait until @roland-sipos says something and then we can merge, so I can move on onto the microservice.

**Pull request merged**
